### PR TITLE
sys_fs: use sys_fs.Error when open_mode is null

### PR DESCRIPTION
**Pull request by dbz400**
Make Puzzle Quest: Challenge of the warlords works (NPUB30041)

### CODE REVIEW

**Comment by dbz400** [comment]
@vlj , this game worth checking .GL backend renders pretty good while D3D12 backend is quite broken.

**Comment by vlj** [comment]
Here the game fails to load with 

E {SPU[0x22f] Thread (_Multistream SPU Thread)[0x00000000]} Unknown STOP code: 0x0
E {SPU[0x22f] Thread (_Multistream SPU Thread)[0x00000000]} Exception: SPUThread::stop_and_signal
E {SPU[0x22f] Thread (_Multistream SPU Thread)[0x00000000]} Information: is_alive=1, m_last_syscall=0x0 ()

Otherwise the loading screen is the same on d3d12 and GL...

**Comment by dbz400** [comment]
Once reach the title screen and "press start to continue" , then difference below 

-GL
gl

-DX12
d12

**Comment by vlj** [comment]
Can't really say what's happening there. I noticed that the loading script is flickering with dx12 but not with GL though.

**Comment by dbz400** [comment]
Yep , the flickering is quite serious indeed :)

**Comment by vlj** [comment]
if I increase command buffer size the flickering disappears. I'm investigating if there is a way to handle the buffer logic that doesn't break games in the process.

**Comment by vlj** [comment]
Command buffer management rework does help but there is still some flickering.

**Comment by dbz400** [comment]
that's good .Meanwhile , i closed the sys_fs_open pull request in master as it breaks the Adreko Series .

(Just seen you haven't revert it and i am now working with Nekotekina for the fix)

https://github.com/Nekotekina/rpcs3/commit/f158d730925546bb5dac0e80bd1be8c9dc2b0a3a

**Pull request merged**
