### PR TITLE
d3d12: msic minor fixes

### PR DESCRIPTION
**Pull request by dbz400**
Make pm_zcull.ppu.elf renders correctly.

pm

### CODE REVIEW

**Comment by dbz400** [comment]
@vlj .fw_dice.elf seems to be working though lots of assertions that canAlloc() return false

dice

**Comment by vlj** [comment]
the dice test is stressing the backend because there are a lot of draw calls, I allocate 128 mb for vertex and constant data, if I use 512 mb it works but then memory consumption is very high... 
constant data memory usage can be improved, it currently requires a alignment of 64kb in heap while each buffer is between 255 and 2kb in size, so a lot of space is wasted. 
vertex data is much more complicated to handle since the 64 kb alignment is mandatory. The solution here is to do per frame vertex caching (ie reuse vertex buffer when they're mapping to the same memory range in ps3 memory) like I do for textures. Unfortunately it's harder for vertex buffer since there is no way to know where vertex buffer starts and ends ;  the solution here is to use tiled memory.

**Comment by dbz400** [comment]
I see and that explained why it renders with 0.5 fps only.

**Comment by vlj** [comment]
With latest commit it should work, I tweaked the heap value and made change to constant buffers managements. The vertex heap is 384 mB big, constant heap is 64 mB, prior they were respectively 128 and 128 so memory requirement is increased.

**Comment by dbz400** [comment]
Yep , it works now

**Pull request merged**
